// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: post.sql

package db

import (
	"context"
	"time"
)

const createOnePost = `-- name: CreateOnePost :exec
INSERT INTO posts (id, title, body, author_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOnePostParams struct {
	ID        string
	Title     string
	Body      string
	AuthorID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateOnePost(ctx context.Context, arg CreateOnePostParams) error {
	_, err := q.db.ExecContext(ctx, createOnePost,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
